### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/scratch-blocks#18]
I cloned the repo, made some changes, connected it to my scatch-gui, but my changes aren't coming into effect.
How can I make it work?

**Comment by CubesterYT** [comment]
First of all, you need some prerequisites:
 - NodeJS
 - Python
 - Java

Once you have them installed. In order to update your builds, use this command `npm run prepublish` to build scratch blocks, which will be used in your gui.

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/scratch-blocks?tab=readme-ov-file#local-development

**Comment by veggiecan0419** [comment]
Thanks. What I mean is not locally, I mean on github I am trying to deploy my project.
I have set the package src to be my github repo. Then I made some changes to my repo, but it didn't update

**Comment by veggiecan0419** [comment]
https://github.com/BlockScript/scratch-blocks

**Comment by CubesterYT** [comment]
The github repo doesn't expose the builds. Make a branch called "develop-builds"; This should be the linked repo. In this branch, expose the builds by removing them from gitignore and uploading the builds to that branch.

**Comment by veggiecan0419** [comment]
So I have to do it manually every time?

**Comment by CubesterYT** [comment]
Yes, you do. Unless you automate it using github actions.

**Comment by veggiecan0419** [comment]
@CubesterYT Thanks!
